### ISSUE TITLE
Descriptive metadata: add geo extension schema to openapi

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/cocina-models#170]
The geo extension schema needs to be added to openapi in order to complete https://github.com/sul-dlss/dor-services-app/pull/1163.

@arcadiafalcone

**Comment by andrewjbtw** [comment]
Has this been completed? https://github.com/sul-dlss/dor-services-app/pull/1163 has been merged.

**Comment by arcadiafalcone** [comment]
It looks like it has been.
