### ISSUE TITLE
Automate cocina-models gem update deployment

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#176]
As documented in the README, cutting a new cocina model gem and upgrading all of the relevant applications is extremely time consuming. On the other hand, not cutting a new cocina model is risky because (1) it puts more changes into a single update; (2) it allows time to pass between a change to cocina model and fixes to dependent application; and (3) it makes it difficult/slow to push out a production fix.

Such automation would:
1. Cut a new cocina models gem.
2. Update dor-services client and cut a new gem.
3. Update sdr-client and cut a new gem.
4. Update sdr-api with new gems and openapi.
5. Update dor-services-app with new gems and openapi.
6. ✅ SCRIPTED! Update all other dependent apps with new gems.  
    a. **~~script to make PRs to update gems~~** (see sul-dlss/access-update-scripts/pull/181)
    b. ~~**script to merge all these PRs** (idea:  have a way to run "merge_all.rb" to selectively merge these PRs.~~ (see sul-dlss/access-update-scripts/pull/187)
7. ✅ SCRIPTED! Deploy all updated apps.
    ~~**script to deploy all these apps PLUS dor-services-app and sdr-api** (idea:  have a way to run sdr_deploy to selectively deploy these apps)~~ https://github.com/sul-dlss/sdr-deploy/pull/93

**Comment by ndushay** [comment]
` gem dependency -R cocina-models` shows the gems directly dependent on cocina-models (dor-services-client and sdr-client)

**Comment by ndushay** [comment]
I'm not sure if steps 1-3 are worth updating ... what do you think?   @jcoyne

**Comment by ndushay** [comment]
personally, I think this is about as automated as we can make it, given the potential need to manually check for openapi.yml changes and edit those files.  Should this ticket be closed?  A new one can be opened if someone has ideas for how to automate further ...

**Comment by justinlittman** [comment]
Agree.
