### ISSUE TITLE
Question: is geographic data mapped to Cocina?

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/cocina-models#211]
When I look at the Cocina model for an object and don't see all the data mapped there, should I assume it's not mapped?

Example:

- This item has a geoMetadata datastream: https://argo.stanford.edu/view/bq841qm7759
- The Cocina model for that item has no "geographic" subsection (though this is part of the Cocina API)
- There is geographic data within the "description" subsection (from the MODS?)

Does that mean the data is not mapped yet? This item has been released to Earthworks, so the data published to the Purl needs to include geodata. If we took Fedora out of the process, would the Purl still publish with the right data?

**Comment by jcoyne** [comment]
There is a field for it in cocina-models (iso19139), however it doesn't look like the mapping is happening in dor-services-app.

**Comment by andrewjbtw** [comment]
I think the answer to this is now: yes.
