### ISSUE TITLE
Add version label to cocina data model

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/cocina-models#232]
https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/dro.rb#L32

Per discussion, we need to track the current version's label.

**Comment by jcoyne** [comment]
What about version tag?  Who opened it? Who closed it? When?

**Comment by ndushay** [comment]
next step:  a meeting to discuss?   Andrew exploring what we have now in events and such a bit ???

**Comment by ndushay** [comment]
this is relevant to DSA/Fedora decoupling.

**Comment by justinlittman** [comment]
Version label is moving to DB, so closing.
