### ISSUE TITLE
Ensure we are mapping all data from rightsMetadata to Cocina

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/cocina-models#236]
The `<rightsMetadata>` can include a number of statements, plus code for licenses. We don't appear to be mapping all of this to Cocina.

Example: https://argo.stanford.edu/view/druid:bb001xb8305

Fedora rightsMetadata:

```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world/>
    </machine>
  </access>
  <use>
    <human type="creativeCommons">Public Domain Mark 1.0</human>
    <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/mark/1.0/">pdm</machine>
    <human type="useAndReproduction">This material is believed to be in the public domain. There are no restrictions on use of public domain materials.</human>
  </use>
  <copyright>
    <human>Public Domain.</human>
  </copyright>
</rightsMetadata>
```

Current Cocina for that object:

```json
{
    "access": "world",
    "copyright": "Public Domain.",
    "download": "world",
    "useAndReproductionStatement": "This material is believed to be in the public domain. There are no restrictions on use of public domain materials."
}
```
For this example, we appear to be missing mappings for:

```xml
<human type="creativeCommons">Public Domain Mark 1.0</human>
    <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/mark/1.0/">pdm</machine>
```

**Comment by jcoyne** [comment]
@andrewjbtw do you know how these are set?  I didn't see any projects that are setting this: https://github.com/search?q=org%3Asul-dlss+creative_commons&type=code

**Comment by andrewjbtw** [comment]
Two places I know of:

- Edit APO form "default use license" dropdown -- it might fill in the human statement too since I don't see a field for that
- rightsMetadata direct edits because if it's not in the menu and people find they need it, they might just write in themselves if there's a need to do it

**Comment by jcoyne** [comment]
Is there a way to see this value somewhere other than in the xml?

**Comment by andrewjbtw** [comment]
Old Argo ticket about editing the defaultObjectRights datastream in the past to support CC 4.0: https://github.com/sul-dlss/argo/issues/1394

**Comment by andrewjbtw** [comment]
Not in Argo currently but it's included in the proposed new design. The new design should display all the data that is editable and not obscure things like the current one.

The other place to see it is the Purl. But I think there are some questions about how the Purl is interpreting the data https://github.com/sul-dlss/purl/issues/321 and maybe also https://github.com/sul-dlss/purl/issues/472

**Comment by mjgiarlo** [comment]
@ndushay @jcoyne @andrewjbtw I... ***think***... all the tendrils of this have been accounted for, whether done or ticketed. Is that y'all's understanding as well? If so, let's close the issue?

**Comment by ndushay** [comment]
lemme close it as part of #2701
