### ISSUE TITLE
cocina access download values: let's simplify!

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/cocina-models#242]
access.download values may be unnecessarily complicated.

allowed access.download values:
- none (default)
- world
- stanford
- location-based

allowed access.access values:
- dark (default)
- world
- stanford
- location-based
- citation-only

Assumptions:
- we will NEVER allow download to be MORE permissive than the access value.
- citation-only and dark are NEVER allowed to download (how it works with rightsMetadata.xml interpretations now)
- it doesn't make a lot of sense to have download values that don't match the access value, with the exception of none.

so effectively, we have 
- world/world
- world/none
- stanford/stanford
- stanford/none
- location-based/location-based  (seriously?  download location based?  that's bizarre, no?)
- location-based/none

which could be expressed as a boolean that might be called "prohibit-download" or something.   It could default to false, since most things allow downloads, or it could default to true because at some point someone decided access.download should default to "none" (which is the opposite of how we handled it in Fedora).

**Comment by ndushay** [comment]
tagging @andrewjbtw as "the Arcadia of cocina access"

**Comment by andrewjbtw** [comment]
I don't think we can simplify because we have examples of:

access: world
download: stanford (but not world)

See https://argo-stage.stanford.edu/view/druid:nn734fw1198 which matches a real set of prod objects.

**Comment by andrewjbtw** [comment]
location-restricted no-download is an odd one but matches an actual use case. I'm not sure how Stanford sets up the reading room computers, but when I was an archivist we did have to make a distinction (for legal reasons) between:

- available on a computer we supplied in the reading room, but we can't give you a copy
- available on a computer we supplied in the reading room, but you are free to copy what you want

Of course, if the library controls the computer, the library also controls whether people can plug in USB drives or otherwise make copies of downloaded materials. But I don't know how these reading-room usages are managed in the real world.

**Comment by ndushay** [comment]
I'm hearing you.  So how would we express https://argo-stage.stanford.edu/view/druid:nn734fw1198  in cocina?

access = world
download = stanford 

and then ... what does it mean that a file can be world accessed when we've already said the whole collection can be world accessed?

```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <group>stanford</group>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world rule="no-download"/>
    </machine>
  </access>
  <access type="read">
    <file>nn734fw1198_md.pdf</file>
    <machine>
      <world/>
    </machine>
  </access>
  <use>
    <human type="creativeCommons">Public Domain Mark 1.0</human>
    <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/mark/1.0/">pdm</machine>
    <human type="useAndReproduction">default use and reproduction</human>
  </use>
  <copyright>
    <human>default copyright</human>
  </copyright>
</rightsMetadata>
```

**Comment by jcoyne** [comment]
one way that could be expressed is:
```
object:
  download: stanford
  access: world
  
file (nn734fw1198_md.pd):
  download: world
  access: world
  
file (*):
  download: stanford
  access: world
```

However, that rights XML is very unclear.  We have two stanza's without qualifiers, which seems really challenging to reason about and to know how these rules combine, (additive or subtractive) and which has precedence:
```
  <access type="read">
    <machine>
      <group>stanford</group>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world rule="no-download"/>
    </machine>
  </access>
```

**Comment by ndushay** [comment]
adding @mjgiarlo to this as this is right in the pocket of what his dor-services-app sul-dlss/dor-services-app#2402 PR is trying to do

**Comment by mjgiarlo** [comment]
This is gonna be difficult to absorb asynchronously. Do we need a meeting to follow up last week's related rights MD mapping meeting? Thanks for tagging me in, @ndushay!

**Comment by mjgiarlo** [comment]
Also, FWIW, I am totally happy to walk away from #2402 if my being away is holding things up.

**Comment by andrewjbtw** [comment]
My understanding of this mapping is the same as what @jcoyne outlines:

object:
  download: stanford
  access: world
  
file (nn734fw1198_md.pdf):
  download: world
  access: world

The remaining files would not have access or download set explicitly in their file-level structural metadata. Instead, they would all get the rights that have been set at the object level. This matches what we do in the XML where individual files have rights set explicitly only if those rights differ from the object level.

If we can express this more clearly with a different way of constructing the cocina model for access, I'm open to that. At the rights meeting I thought we would need to change the model, but an outcome of the discussion was that we would try to map cases like this in the existing Cocina structure.
