### ISSUE TITLE
embargo release access rights values should support all values in the Argo rights menu

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/cocina-models#253]
from https://argo.stanford.edu/catalog?f%5BobjectType_ssim%5D%5B%5D=item

as the issue title says:  embargo release access rights values should support all values in the Argo rights menu:

![image](https://user-images.githubusercontent.com/96775/114796180-2bea1f00-9d45-11eb-90c5-06b5b7f483eb.png)

Per @andrewjbtw, the cocina embargo model should support all these settings.  With a bit of a dither:

> I should add that arguably, an embargo should only support increasing rather than limiting access but
> 
> - it may be simpler to show the same rights menu here as elsewhere instead of customizing just for embargoes
> - only citation-only and dark would be excluded if we excluded anything
> - the idea was suggested for digital borrowing that items could be set to "expire" at the end of the quarter by automatically changing to citation-only or dark via embargo release. We have not been asked to implement this but it also has not been categorically ruled out.

(so consider the above, think about whether this restriction should happen HERE or in Argo (see sul-dlss/argo/issues/2674) and possibly double check with andrew before setting a PR for this ticket as "ready for review."  My gut reaction is that the restriction should happen in Argo and/or dor-services-app)

Currently we have the possibilities as https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/embargo.rb#L10 

![image](https://user-images.githubusercontent.com/96775/114794279-f7746400-9d40-11eb-88f0-31129d7c3f8b.png)

but note that the nuances are expressed differently in https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/access.rb with separate attributes for `readLocation`:

![image](https://user-images.githubusercontent.com/96775/114794312-0eb35180-9d41-11eb-8564-bdd5c29a2e35.png)

And that the `download` attribute is specified in 

https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/admin_policy_default_access.rb
https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/dro_access.rb
https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/file_access.rb

**Comment by andrewjbtw** [comment]
I should clarify that I mean the rights menu, which is not as wide-open as the rights facet since that picks up many hand-created settings:

<img width="1131" alt="Screen Shot 2021-04-14 at 5 11 00 PM" src="https://user-images.githubusercontent.com/8975583/114795873-7dde7500-9d44-11eb-8059-f30e4568b1fd.png">

**Comment by ndushay** [comment]
fixing in tickets - thanks
