### ISSUE TITLE
create a new property for download location

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/cocina-models#258]
Currently it's possible to have the following access:
```json
    "access": {
        "access": "world",
        "download": "location-based",
        "readLocation": "m&m"
    }
 ```

which means an one can read/stream the object, but it should only be downloadable in the `m&m` reading room.  However, the property says "read" and we are abusing it for "download".   It would be more clear if there was a separate property called `downloadLocation`.

**Comment by ndushay** [comment]
Is this still a thing?  Should it be in the ADR / google doc?

**Comment by jcoyne** [comment]
I think so

**Comment by ndushay** [comment]
adding to google doc now

**Comment by justinlittman** [comment]
Replaced by #332
