### ISSUE TITLE
DROStructural:  no agreements, only APOs have them.  APOs should REQUIRE agreementId

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/cocina-models#259]
1.  Currently DROStructural contains "hasAgreement" but per @andrewjbtw:

> items don’t need to have agreements anywhere
> the reference back to agreements is just supposed to be in the APO RELS-EXT

2. require agreementId for AdminPolicy objects (in adminPolicyAdminstrative as "referencesAgreement" )

**Comment by ndushay** [comment]
@andrewjbtw double checking:   are you ok with the agreementId being removed from every DRO as it is updated?  It would still be available via the admInPolicy.    (alternatively, did you mean we should keep the agreementId in every cocina DROStructural, and only remove it from Fedora identityMetadata.xml ?)

**Comment by jcoyne** [comment]
isMemberOf is in structural as the relationship between items and the collections they are members of was deemed to be a structural concern when we were designing the schema.

**Comment by ndushay** [comment]
more background here:  https://docs.google.com/document/d/1Oa4bkeLsv9q1kDN_496fRBLguP6VFE79LbxQq6vxeHY/edit#heading=h.ey5hfnci03kz

**Comment by ndushay** [comment]
See sul-dlss/dor-services-app/issues/2817 for the DSA mapping part of this work.

**Comment by justinlittman** [comment]
@andrewjbtw Can you let us know when https://github.com/sul-dlss/dor-services-app/issues/3142#issuecomment-1017696461 is completed so that can unblock this work?

**Comment by andrewjbtw** [comment]
@justinlittman the cleanup is done
