### ISSUE TITLE
canonical purl should start with "https"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/cocina-models#276]
The string for the canonical purl should start with https rather than http. Unfortunately, there seems to have been some unclear communication around this and we are currently treating http as the valid string (see https://github.com/sul-dlss/cocina-models/pull/266 ).

I'm not sure where else this change needs to be made but undoubtedly it affects a number of other codebases.

**Comment by jcoyne** [comment]
Changes need to be made in DSA and H2 which currently normalize `https://purl.stanford.edu` to `http://purl.stanford.edu`
