### ISSUE TITLE
Model APO Identification with sourceId field

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#289]
Currently, Cocina supports identification > sourceId for Collections and DROs. For this ticket, create sourceId for APOs. It is not required.

**Comment by jcoyne** [comment]
Why do we want to do this? What does a "source id" of an APO represent?  What is the source of an APO?  I know we have old hydrus APOs that have a source id, but it isn't used for anything.

**Comment by andrewjbtw** [comment]
Amy and Hannah have wanted to keep that data since the source id gives some information about how a Hydrus APO was created (the sunet and date). I can check if they still think it's useful to have now that H2 has been running for a while without the specific APOs.

**Comment by andrewjbtw** [comment]
Source ID can be removed from APOs. I have a way to get that data into the descMetadata if it needs to be looked up later. I still need to update the descMetadata before Fedora goes away but the source id doesn't need to be mapped.
