### ISSUE TITLE
Model otherId[type="previous_catkey"]

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#296]
The UpdateMarcRecordService has handling of previous catkeys: https://github.com/sul-dlss/dor-services-app/blob/main/app/models/dor/update_marc_record_service.rb#L53

However, previous catkeys (otherId[type="previous_catkey"] in identity metadata) are not currently mapped and do not have a place in the Cocina data model. 

Should they be mapped? Or can they be dropped?

**Comment by justinlittman** [comment]
@jcoyne Assigning to you to determine how this should be modeled.

I would make the argument for getting rid of `catalogLinks` in favor of separate `symphony_catkeys`, `symphony_previous_catkeys` and (in the future adding) `folio_keys`. I'm already growing tired of writing `catalogLinks.find {|link| link.catalog == 'symphony'}` instead of `symphony_catkey.first`.

**Comment by justinlittman** [comment]
Once this is completed, unblock https://github.com/sul-dlss/dor-services-app/issues/3235

**Comment by jcoyne** [comment]
Do we need to store previous catkeys in the model, or can we have an api call that can return all the old catkeys across all versions? That seems to me a more sensible way, as once a catkey is set, then it can never be lost.

**Comment by justinlittman** [comment]
How would that work with existing previous catkeys (since we'll lose previous versions pre-postgres)?

**Comment by jcoyne** [comment]
We could construct the version history from the fedora versions, or we could put these in a separate table.  I believe "past catkeys" is just administrative metadata and doesn't need to be preserved.

**Comment by justinlittman** [comment]
The decision was to use the existing model, with a catalog key of "previous symphony".
