### ISSUE TITLE
Remove referencesAgreement

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#298]
As it is redundant of `hasAgreement`.

See https://github.com/sul-dlss/cocina-models/blob/main/openapi.yml#L238-L241

**Comment by jcoyne** [comment]
I don't believe we use `referencesAgreement` anywhere.

**Comment by justinlittman** [comment]
Turns out we did, but I changed to `hasAgreeement` with last cocina models change. I'm going to remove `referencesAgreement`.

**Comment by justinlittman** [comment]
Done.
