### ISSUE TITLE
remediate cocina for ETDs, then remove ETD specific Vocab::Resource types

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/cocina-models#302]
Depends on sul-dlss/dor-services-app/issues/3298

Per discussion with infra team and Andrew on 2/3/2022, we have agreed that the following ETD specific Resource types are deprecated.  We want to remove them after all SDR objects have been remediated so they aren't used.

- `Cocina::Models::Vocab::Resources.main-original`
- `Cocina::Models::Vocab::Resources.main-augmented`
- `Cocina::Models::Vocab::Resources.supplement`
- `Cocina::Models::Vocab::Resources.permissions`

Depends on:
- changing existing ETDs that use these to use `Cocina::Models::Vocab::Resources.file` instead

**Comment by ndushay** [comment]
We don't currently know of a way to deprecate these in cocina-models (and have the deprecation messages put someplace useful).

**Comment by justinlittman** [comment]
@ndushay We can just change the mapping in DSA to make these not appear in the mapping. There is no need to do any remediation.

**Comment by ndushay** [comment]
@justinlittman please ticket it appropriately.

**Comment by ndushay** [comment]
this is now done!  Yay!
