### ISSUE TITLE
Change height and width to be numbers

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#306]
The datatype is currently integers.

See https://github.com/sul-dlss/dor-services-app/issues/3405

**Comment by jcoyne** [comment]
@justinlittman the access team is just casting these values to integers anyway, are we sure this is necessary?

**Comment by justinlittman** [comment]
Just because the access team currently handles this incorrectly doesn't mean they always will in the future and we should throw away data.

**Comment by justinlittman** [comment]
Decided to retain integers.
