### ISSUE TITLE
Add TitleBuilder and RightsDescriptionBuilders as utility methods

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/cocina-models#311]
This would include extracting TitleBuilder: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/title_builder.rb and *RightsDescriptionBuilders (e.g. https://github.com/sul-dlss/dor_indexing_app/blob/main/app/services/dro_rights_description_builder.rb) We also might consider putting the MODS<-> cocina mappings in there. 

This is helpful because we already have copied code between DSA and DIA for building titles.  If we have this as an available library it could allow easier adoption of the cocina model by the access team and would allow for refactoring in Argo.

**Comment by mjgiarlo** [comment]
Additionally, I wonder if we want cocina-models to define one or more RSpec matchers for downstream codebases. We are already seeing these duplicated (DSA, Argo).

**Comment by ndushay** [comment]
I like Mike's idea about rspec matches in cocina-models as needed.   Can that be ticketed (for specific matchers we already use?)

**Comment by ndushay** [comment]
In fact, can all the re-used "interpret this data in the cocina model" code be ticketed ?

**Comment by jcoyne** [comment]
@mjgiarlo feel free to make matchers as a separate ticket.

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> @mjgiarlo feel free to make matchers as a separate ticket.

https://github.com/sul-dlss/cocina-models/issues/319
