### ISSUE TITLE
Add enums to the structs when enums are in the openapi.yml

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/cocina-models#313]
See https://dry-rb.org/gems/dry-types/1.0/enum/

Start with file access.  Once complete, this should raise an error:

```ruby
Cocina::Models::FileAccess.new(access: 'citation-only', download: 'none')
```

**Comment by justinlittman** [comment]
So that would kinda help, but not stop this:
```
Cocina::Models::FileAccess.new(access: 'world', download: 'stanford', controlledDigitalLending: true)
```
which is invalid in openapi.yml.

Instead, I would suggest that we validate on `instance.new`, not just `class.new`.

**Comment by jcoyne** [comment]
Yeah, that sounds better.
