### ISSUE TITLE
Define Cocina RSpec matchers

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/cocina-models#319]
Occasionally when downstream codebases are testing Cocina structures, they are creating custom Cocina matchers. These matchers could live in the cocina-models gem so that they don't have to live everywhere else. Ensure each of the above codebases' test suites pass once they pick this up from cocina-models:

- [x] https://github.com/sul-dlss/dor-services-app/blob/main/spec/support/cocina_matchers.rb
- [x] https://github.com/sul-dlss/argo/blob/main/spec/support/cocina_matchers.rb
- [x] https://github.com/sul-dlss/sdr-client/blob/main/spec/support/cocina_matchers.rb

Also:

- [x] Describe the matcher(s) in the README

**Comment by mjgiarlo** [comment]
@jcoyne @justinlittman heads-up. prioritize as you will, sirs.

**Comment by justinlittman** [comment]
Please make sure these matchers are described in README.
