### ISSUE TITLE
Create license vocabulary

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#344]
That contains `https://cocina.sul.stanford.edu/licenses/none`.

`http://cocina.sul.stanford.edu/licenses/none` (notice the `http` not `https`) is hardcoded in many codebases.

**Comment by ndushay** [comment]
can we just use the Cocina Models vocabulary?  Should this be Cocina::Models::License  vocab that is generated?

**Comment by jcoyne** [comment]
Fixed by #350
