### ISSUE TITLE
Remove hardcoding of none license

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#345]
Blocked by #344

Instances can be found in the code / specs of:

- [ ] dor-services-app
- [ ] dor_indexing_app
- [ ] hydra_etd
- [ ] sdr-api

**Comment by justinlittman** [comment]
This needs a cocina models gem first.

**Comment by jcoyne** [comment]
@justinlittman it sounds like we should revise this ticket and remove the use of this?
