### ISSUE TITLE
Generate user documentation from description validation files

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/cocina-models#385]
In order to prevent having to maintain documentation of evolving validation standards in multiple places, it would be useful to be able to automatically generate user-readable documentation directly from the YAML configuration file for type validation.

Some notes on the conversion:
1. The section header in the YAML file is converted to separate words + "types", so contributor.name becomes "Contributor name types"
2. If the section header ends with structuredValue, "part types for structured value" is added in the markdown, so contributor.name.structuredValue becomes "Contributor name part types for structuredValue"
3. If the section header ends with groupedValue, "types for grouped value (MODS legacy)" is added in the markdown, so contributor.name.groupedValue becomes "Contributor name types for grouped value (MODS legacy)"

**Comment by arcadiafalcone** [comment]
Sample Markdown file with selections from description_types.yml
[documentation_test.md](https://github.com/sul-dlss/cocina-models/files/8474879/documentation_test.md)

**Comment by mjgiarlo** [comment]
have an in-progress PR up: https://github.com/sul-dlss/cocina-models/pull/396 with thoughts on how we might proceed

Unassigning on my way out for the week 👋🏻

**Comment by justinlittman** [comment]
@arcadiafalcone @andrewjbtw Here it is: https://sul-dlss.github.io/cocina-models/description_types.html
