### ISSUE TITLE
Date validation

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#392]
From sul-dlss/argo#3375, validates dates (per @arcadiafalcone )
```
Date encodings

w3cdtf, edtf, iso8601
Year:
YYYY (eg 1997)
Year and month:
YYYY-MM (eg 1997-07)
Complete date:
YYYY-MM-DD (eg 1997-07-16)
Complete date plus hours and minutes:
YYYY-MM-DDThh:mm (eg 1997-07-16T19:20)
Complete date plus hours, minutes and seconds:
YYYY-MM-DDThh:mm:ss (eg 1997-07-16T19:20:30)
Complete date plus hours, minutes, seconds and a decimal fraction of a second
YYYY-MM-DDThh:mm:ss.s (eg 1997-07-16T19:20:30.45)
Complete date plus hours and minutes with time zone:
YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
Complete date plus hours, minutes and seconds:
YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
Complete date plus hours, minutes, seconds and a decimal fraction of a second
YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)

edtf
-YYYY (eg -3999)

iso8601
YYYYMMDD
YYYYMMDDThhmm
YYYYMMDDThhmmss
YYYYMMDDhhmm
YYYYMMDDhhmmss
YYYYMMDDThhmmss.s+
YYYYMMDDhhmmss.s+
```

**Comment by arcadiafalcone** [comment]
Additional ISO 8601 date patterns:
```
YYYYMMDDThhmmss.s+
YYYYMMDDhhmmss.s+
```

**Comment by arcadiafalcone** [comment]
@jcoyne Yes, that would be great.

**Comment by mjgiarlo** [comment]
@arcadiafalcone I've run these values through a couple different EDTF validators and they show as invalid for EDTF:

* `1997-07-16T19:20`
* `1997-07-16T19:20:30.45`
* `1997-07-16T19:20+01:00`
* `1997-07-16T19:20:30.45+01:00`

What are your thoughts on how we should proceed?

**Comment by arcadiafalcone** [comment]
According to the LC EDTF specification (https://www.loc.gov/standards/datetime/) those all appear acceptable. I'm curious why they're not passing, but they should be considered valid.

**Comment by mjgiarlo** [comment]
@arcadiafalcone 💬 
> According to the LC EDTF specification ([loc.gov/standards/datetime](https://www.loc.gov/standards/datetime/)) those all appear acceptable. I'm curious why they're not passing, but they should be considered valid.

I'll have a look.

**Comment by arcadiafalcone** [comment]
@mjgiarlo Now I'm thinking it's better to start with the built-in validation and see if we have any data that matches these questionable patterns. Remediation may be the preferable route if we have inconsistencies.

**Comment by mjgiarlo** [comment]
@arcadiafalcone Now that this is in the cocina-models gem, when should we hook it up/turn it on? e.g., did you want to take a look at the three bad date reports first? (two of which are still being run now...)

**Comment by arcadiafalcone** [comment]
@mjgiarlo I'd like to review the reports first. I'll give you the all-clear when it's ok to turn on.
