### ISSUE TITLE
Generate user documentation from descriptive metadata model in openapi.yml

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/cocina-models#395]

**Comment by justinlittman** [comment]
Dupe of #385

**Comment by arcadiafalcone** [comment]
This is different - it's creating documentation of the descriptive model (from a subset of openapi.yml) rather than the type vocabulary (description_types.yml).

**Comment by arcadiafalcone** [comment]
Description created in Consul instead.
