### ISSUE TITLE
Descriptive identifier type with hash not validating

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/cocina-models#412]
https://github.com/sul-dlss/cocina-models/blob/f8001c2784549821e09840226cbb90fc18ac1cd4/description_types.yml#L359

What is the correct way to escape this character?

**Comment by ndushay** [comment]
@arcadiafalcone I suggest you put the value in quotes like this:

```yml
- value: 'West Mat #'
```

**Comment by ndushay** [comment]
I am going to write a test (rspec) for this right now.
