### ISSUE TITLE
Refactor:  rename mapping folders "to_mods" and "from_mods", etc.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/cocina-models#431]
Since mapping to and from MODS is going to be with us for a while, but Fedora is going away, we should change the name of these two folders in app/services/cocina 

There is also inconsistency in class names:

should it always be name for the MODS element?  for the Cocina class?  For the originating object?    We have, for example, "contributor" and "name_builder" classes in the from_fedora mods code.

**Comment by justinlittman** [comment]
This should be under `Cocina::Models::Mappings` ...

**Comment by ndushay** [comment]
the h2 access, admin_metadata mappings:  files need renaming to correspond to mods...

**Comment by ndushay** [comment]
And ... this is now done.
