### ISSUE TITLE
Retain role in name subject in Cocina>MODS direction

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/cocina-models#465]
Example of role being dropped: compare Cocina and published purl MODS for name subject "Brandin, Alf" in dv559gn8984.

See spec at https://github.com/sul-dlss/cocina-models/blob/9c9c0ce7f9e8002aa1e80233d1a4741f0a7e0a06/spec/cocina/models/mapping/descriptive/mods/subject_name_spec.rb#L809

**Comment by justinlittman** [comment]
@arcadiafalcone I'm not entirely clear on this. Can you provide a spec?

**Comment by arcadiafalcone** [comment]
For the above example druid dv559gn8984, the output MODS is
```
<subject authority="lcsh">
  <topic>Stanford Shopping Center</topic>
  <name type="personal">
    <namePart>Brandin, Alf</namePart>
  </name>
  <topic>Stanford Industrial Park</topic>
</subject>
```
and should be
```
<subject authority="lcsh">
  <topic>Stanford Shopping Center</topic>
  <name type="personal">
    <namePart>Brandin, Alf</namePart>
    <role>
      <roleTerm type="text">interviewee</roleTerm>
    </role>
  </name>
  <topic>Stanford Industrial Park</topic>
</subject>
```
