### ISSUE TITLE
Map literal <i> and <cite> elements in note fields to be wrapped in CDATA

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/cocina-models#482]
The Martin Wong collection (among others) requires that `<i></i>` and `<cite></cite>` HTML elements are not stripped out and are mapped to be wrapped in CDATA, particularly within note fields. The current behavior escapes these elements, e.g., `&lt;i&gt;` (which does work in PURL but produces invalid MODS and is not the specified approach).

To make testing easier, we've already created a CSV that is a subset of actual Martin Wong data:

[Martin_Wong_sample.csv](https://github.com/sul-dlss/modsulator-app-rails/files/8826081/Martin_Wong_sample.csv)

You can test that here: https://argo-stage.stanford.edu/apos/druid:bc036dg9936/bulk_jobs (choose `Spreadsheet input; load into objects` after selecting said CSV file.)

Here is the test object in Argo: https://argo-stage.stanford.edu/view/druid:hb400xn4539
And here's its PURL page to ensure italics (around `Paiting is Forbidden` in the exhibition history note) are present: https://sul-purl-stage.stanford.edu/hb400xn4539

In addition to PURL, we should also ensure that the italics make it through to Exhibits (both on the item show page and in the "More details" view). If you need to consult the Access team for help with either or both of these, they will have time for this between 6/6 and 6/24.

Connects to sul-dlss/exhibits#1981

**Comment by mjgiarlo** [comment]
@jcoyne What's left on italics is I think to put this code in place and verify it has the desired effect on the Access side.

**Comment by andrewjbtw** [comment]
The cocina version on [kd791zq6661](https://argo-stage.stanford.edu/view/druid:kd791zq6661) is showing as 0.80.0 not 0.82.0

**Comment by andrewjbtw** [comment]
Although in the public XML it's showing as 0.82.0

**Comment by mjgiarlo** [comment]
Closed by https://github.com/sul-dlss/cocina-models/pull/481
