### ISSUE TITLE
[BLOCKED] Turn on datetime validation for known types

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/cocina-models#485]
Now that we have a [datetime validator](https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/validators/date_time_validator.rb) in cocina-models, we want to turn it on once the related [datetime reports in dor-services-app](https://github.com/sul-dlss/dor-services-app/tree/main/app/reports) all run clean. Once they run clean, this issue will no longer be blocked and will be ready to work on.

- [x] Make changes to the datetime validator that were made on the report side (covered by tests)
  - [x] Update the W3CDTF regex to `/\A\d{4}(-0[1-9]|-1[0-2])?\Z/`
  - [x] Allow EDTF failures matching `/\AY-?\d{5,}\Z/` to be considered valid
- [x] Add to [validators list](https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/validators/validator.rb#L8-L16)
- [ ] [Test validation changes](https://github.com/sul-dlss/cocina-models#testing-validation-changes)

**Comment by arcadiafalcone** [comment]
Thanks. We're down to just a few non-Catalhoyuk invalid dates which have to go through ArcGIS. I can manually remove the encoding from the MODS if those are still being worked on once Catalhoyuk is sorted out. For Catalhoyuk, we are not changing the values, just removing `encoding: "w3cdtf"` from the dates, per consultation with Claudia.

**Comment by ndushay** [comment]
So ... is there an action for someone to take re: converting Catalhoyuk records?   Who will undertake the action(s)?

**Comment by mjgiarlo** [comment]
@ndushay I think the question @sul-dlss/infrastructure-team has to resolve is: what is the best way to remediate metadata for ~144K items and then work with @arcadiafalcone on the resolution.

**Comment by arcadiafalcone** [comment]
@ndushay @mjgiarlo Is there a ticket for the Catalhoyuk work / should I make one?

**Comment by mjgiarlo** [comment]
@arcadiafalcone I don't believe there is one. Sure, please do, and we'll make sure to prioritize it and get it in front of the team.
