### ISSUE TITLE
Add DOI pattern exceptions

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/cocina-models#512]
These druids already have DOIs, but they can't be persisted.  Update the pattern to handle these:

hr045dx8661 | 10.25740/VA90-CT15
wv848yd6100 | 10.25740/syxa-m256
mp388hh4436 | 10.25740/12qf-5243
wd199pm1314 | 10.25740/65j8-6114
vx915bx0661 | 10.25936/629T-BX79

Encode these as exceptions, not a general pattern. as we are committed not to having further exceptions.

**Comment by ndushay** [comment]
- cocina-models PR merged
- cocina-models 0.84.0 released
- sdr-client, dor-services-client PRs to use cocina-models 0.84.0 merged
- sdr-client, dor-services-client gems new version released
- dor-services-app, sdr-api PRs with updated openapi.yml  and gem updates (cocina-models, etc.) released
- cocina level 2 PRs created w jenkins
- cocina level 2 PRs merged with access-update-scripts
- cocina apps tagged with rel-2022-08-23
- cocina apps deployed to stage and integration tests run until they passed.
