### ISSUE TITLE
Remove date exceptions in date validations and re-run reports

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/cocina-models#518]
Identified invalid dates have been remediated and date validation may resume.

And then re-run reports from https://github.com/sul-dlss/dor-services-app/issues/4209 after cocina-models release that removes these exceptions to be sure no new bad dates slipped through.

**Comment by peetucket** [comment]
Note: we believe date validation has been on for about a month now: https://github.com/sul-dlss/cocina-models/pull/506/files

Though there were some exceptions added to prevent problem dates from blowing things up: https://github.com/sul-dlss/cocina-models/pull/517

So perhaps the action for this ticket is really to remove those extra regexes added in that PR #517 above
