### ISSUE TITLE
subject identifier does not always need a source.code when creating MODS

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/cocina-models#538]
DSA will raise a [NoMethodError](https://app.honeybadger.io/projects/50568/faults/89091264#notice-context) when transforming descriptive metadata to MODS and a subject's identifier field lacks a `source.code`.

https://github.com/sul-dlss/cocina-models/blob/0d0ac20a901bb490b2458f4667e112019185687a/lib/cocina/models/mapping/to_mods/subject.rb#L436

@arcadiafalcone shared, "One of `source.code`, `source.value`, or `source.uri` should be required if there is `identifier.value` or `identifier.code`, but not required for `identifier.uri`. The URI is complete in itself, but a value or code needs the source info for it to be uniquely identifying."

**Comment by jcoyne** [comment]
@lwrubel being particular, the identifier lacks a `source` in the HB error you linked to.

**Comment by arcadiafalcone** [comment]
This applies to `identifier` anywhere in the descriptive schema.

**Comment by ndushay** [comment]
So is the "identifier" missing the source, or is the source incorrectly parallel with identifier?

Also - this is from a single collection - how was it loaded, was there a mistake, and can it easily be corrected?

Should we devs do anything?

**Comment by arcadiafalcone** [comment]
The data is correct. We don't usually get this error because we don't usually have RWO identifiers for name subjects, but it was done for this collection. We do use them for `contributor.identifier` (e.g. ORCID) - is the code there doing something different to not get this error?

**Comment by ndushay** [comment]
@lwrubel if you need help with this, give a shout in the channel.
