### ISSUE TITLE
Document how to proceed with non-backwards compatible Cocina model changes.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/cocina-models#551]
Create a document for how to release non-backwards compatible Cocina model changes.

The removal of parallelContributor would be an excellent exemplar to use for this, as it is no longer needed.

**Comment by ndushay** [comment]
@justinlittman has this been addressed with the "migrators" ?   Or is that only part of it?

**Comment by justinlittman** [comment]
Done.
