### ISSUE TITLE
Update CatalogLink definitions in cocina for FOLIO

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/cocina-models#561]
The catalogLink.catalog enumerated list should also include `folio` and `previous folio`.

The regex in catalogLink.catalogRecordId should apply only when the catalog is `symphony` or `previous symphony`. When the record is from FOLIO, it should match the patterns for both migrated and new instance HRIDs.
Migrated from Symphony: `/^a\d+$/`
Migrated from Voyager: `/^L\d+$/`
Created in FOLIO: `/^in\d+$/` (to be confirmed)

Presumably editing openapi.yml is sufficient(?)

**Comment by ndushay** [comment]
what remains for this?  did it roll out on Monday with dependency updates?  If so, close the ticket;  if not, please indicate what is left.

**Comment by mjgiarlo** [comment]
@ndushay What remains is to cut a release of cocina-models and roll that out. I wanted to wait until after dep updates to do that. This is on my plate for this week.

**Comment by mjgiarlo** [comment]
This is now in production. Closing.
