### ISSUE TITLE
Cannot instantiate Folio catalog links from hash

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#574]
```
Dry::Struct::Error:
       [Cocina::Models::SymphonyCatalogLink.new] "folio" (String) has invalid type for :catalog violates constraints (included_in?(["symphony", "previous symphony"], "folio") failed)
```

**Comment by justinlittman** [comment]
See test in https://github.com/sul-dlss/cocina-models/pull/575

cc @mjgiarlo

**Comment by ndushay** [comment]
I think the problem is the missing alpha prefix for the folio identifier;  I am closing this ticket per slack conversation with Justin.  Please reopen if I'm wrong.
