### ISSUE TITLE
Add BCP 47 language field to the file model. 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/cocina-models#637]
We need this to disambiguate multiple language transcriptions for the Nuremberg Trial Archive.  This data will be used to drive the options on the closed caption select widget for the media viewer.

https://www.rfc-editor.org/rfc/rfc4646.txt

**Comment by dinahhandel** [comment]
@andrewjbtw if this is done, is there remediation that needs to happen before https://github.com/sul-dlss/sul-embed/issues/1588 is ready?

**Comment by andrewjbtw** [comment]
Yes, and before that we have to have Argo and Preassembly tickets to support editing the new field. I'm writing those.
