### ISSUE TITLE
[ÜBER] Rename request models

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#69]
To that `request` is a suffix, rather than prefix so that they sort next to the non-request models.

For example, `request_dro` becomes `dro_request`.

This needs to be done in cocina-models but also for every consumer of cocina-models, e.g. https://github.com/search?q=org%3Asul-dlss+requestdro&type=Code

**Comment by ndushay** [comment]
See also #70 - not blocking, but PRs may need to be coordinate / rebased.

**Comment by ndushay** [comment]
code and test code has be DRYed up;  this is no longer needed.
