### ISSUE TITLE
Add tests that verify that request models stay in sync with base models

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#70]
The request version of a model (e.g., `dro_request`) is very similar to the base model (e.g., `dro`), except, perhaps, a required field is optional. This creates the risk that a field will be added to only one of these models and not the other.

Please write a test/tests to check the attributes of these models to make sure they stay in sync (and possibly reduce duplicate tests).

**Comment by ndushay** [comment]
probably:  use rspec shared_examples for tests that need to pass for both base and request models.

Somewhat related to model rename in #69 ...
