### ISSUE TITLE
New "identifier type" request x 2

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/cocina-models#724]
Hello!
We have two identifier types that it would be great to be able to add to the limited set of identifier types here: https://github.com/sul-dlss/cocina-models/blob/main/docs/description_types.md#identifier-types

**First is called "Bates range"** (capitalization doesn't matter): From wikipedia: "Bates numbering is used in the legal, medical, and business fields to place one or more of identifying numbers, date and time marks on images and documents as they are scanned or processed, for example, during the [discovery stage](https://en.wikipedia.org/wiki/Discovery_(law)) of preparations for trial or identifying business receipts."

**Second is "filing number"**: Another identifier pertaining to court filings in a case trial.  To "file" is "to place a paper in the official custody of the clerk of court to enter into the files or records of a case."

**Comment by justinlittman** [comment]
@laurensorensen What sort of timing / priority is required on this change?

**Comment by laurensorensen** [comment]
We have a timeline to deliver this exhibit this summer, aiming for the end of July at the latest. So within 3-4 week time frame would be great, sooner would be even better.

**Comment by justinlittman** [comment]
@arcadiafalcone What do you want to use as the identifiers?

**Comment by arcadiafalcone** [comment]
Pull request with update to description_types.yml: https://github.com/sul-dlss/cocina-models/pull/726

The user-facing docs at https://github.com/sul-dlss/cocina-models/blob/main/docs/description_types.md should be regenerated as well - @justinlittman could you do that and/or show me how?

**Comment by justinlittman** [comment]
closed by #726 

@arcadiafalcone I regenerated, merged the PR, and cut a new cocina models release.

@laurensorensen This should go out with dependency updates early next week.
